In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
dataset = pd.read_csv('jml_penduduk_menurut_kelompok_umur_dan_jenis_kelamin2023.csv')

In [22]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [23]:
print(x)

[['4/1/00' 11499.3 11012.6]
 ['5/9/01' 11237.6 10762.4]
 ['10/14/01' 11316.5 10746.7]
 ['15-19' 11419.7 10714.6]
 ['20-24' 11489.7 10871.1]
 ['25-29' 11509.1 10986.4]
 ['30-34' 11243.9 10845.1]
 ['35-39' 10834.1 10570.3]
 ['40-44' 10274.3 10130.8]
 ['45-49' 9544.2 9514.7]
 ['50-54' 8415.0 8450.9]
 ['55-59' 7133.3 7231.3]
 ['60-64' 5676.6 5813.7]
 ['65-69' 4183.9 4344.5]
 ['70-74' 2695.1 2920.6]
 ['75+' 2314.2 2993.5]
 ['Jumlah/Total' 140786.8 137909.4]
 [nan nan nan]
 ['Catatan' nan nan]
 ['Hasil Proyeksi Penduduk Indonesia 2020-2050 Hasil Sensus Penduduk 2020 (Pertengahan tahun/Juni)/<i>Indonesia Population Projection 2020-2050 Result of Population Census 2020 (mid year/June)\xa0</i>'
  nan nan]]


In [24]:
print(y)

[ 22511.8  22000.1  22063.2  22134.4  22360.9  22495.6  22089.   21404.5
  20405.2  19058.9  16865.9  14364.6  11490.3   8528.4   5615.8   5307.7
 278696.2      nan      nan      nan]


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [26]:
print(x)

[['4/1/00' 11499.3 11012.6]
 ['5/9/01' 11237.6 10762.4]
 ['10/14/01' 11316.5 10746.7]
 ['15-19' 11419.7 10714.6]
 ['20-24' 11489.7 10871.1]
 ['25-29' 11509.1 10986.4]
 ['30-34' 11243.9 10845.1]
 ['35-39' 10834.1 10570.3]
 ['40-44' 10274.3 10130.8]
 ['45-49' 9544.2 9514.7]
 ['50-54' 8415.0 8450.9]
 ['55-59' 7133.3 7231.3]
 ['60-64' 5676.6 5813.7]
 ['65-69' 4183.9 4344.5]
 ['70-74' 2695.1 2920.6]
 ['75+' 2314.2 2993.5]
 ['Jumlah/Total' 140786.8 137909.4]
 [nan 16563.135294117645 16224.623529411763]
 ['Catatan' 16563.135294117645 16224.623529411763]
 ['Hasil Proyeksi Penduduk Indonesia 2020-2050 Hasil Sensus Penduduk 2020 (Pertengahan tahun/Juni)/<i>Indonesia Population Projection 2020-2050 Result of Population Census 2020 (mid year/June)\xa0</i>'
  16563.135294117645 16224.623529411763]]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = ct.fit_transform(x)

In [28]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 60 stored elements and shape (20, 22)>
  Coords	Values
  (0, 6)	1.0
  (0, 20)	11499.3
  (0, 21)	11012.6
  (1, 9)	1.0
  (1, 20)	11237.6
  (1, 21)	10762.4
  (2, 0)	1.0
  (2, 20)	11316.5
  (2, 21)	10746.7
  (3, 1)	1.0
  (3, 20)	11419.7
  (3, 21)	10714.6
  (4, 2)	1.0
  (4, 20)	11489.7
  (4, 21)	10871.1
  (5, 3)	1.0
  (5, 20)	11509.1
  (5, 21)	10986.4
  (6, 4)	1.0
  (6, 20)	11243.9
  (6, 21)	10845.1
  (7, 5)	1.0
  (7, 20)	10834.1
  (7, 21)	10570.3
  (8, 7)	1.0
  :	:
  (11, 21)	7231.3
  (12, 12)	1.0
  (12, 20)	5676.6
  (12, 21)	5813.7
  (13, 13)	1.0
  (13, 20)	4183.9
  (13, 21)	4344.5
  (14, 14)	1.0
  (14, 20)	2695.1
  (14, 21)	2920.6
  (15, 15)	1.0
  (15, 20)	2314.2
  (15, 21)	2993.5
  (16, 18)	1.0
  (16, 20)	140786.8
  (16, 21)	137909.4
  (17, 19)	1.0
  (17, 20)	16563.135294117645
  (17, 21)	16224.623529411763
  (18, 16)	1.0
  (18, 20)	16563.135294117645
  (18, 21)	16224.623529411763
  (19, 17)	1.0
  (19, 20)	16563.135294117645


In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [30]:
print(y)

[15  9 10 12 13 14 11  8  7  6  5  4  3  2  1  0 16 17 17 17]


In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [32]:
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 48 stored elements and shape (16, 22)>
  Coords	Values
  (0, 0)	1.0
  (0, 20)	11316.5
  (0, 21)	10746.7
  (1, 14)	1.0
  (1, 20)	2695.1
  (1, 21)	2920.6
  (2, 2)	1.0
  (2, 20)	11489.7
  (2, 21)	10871.1
  (3, 19)	1.0
  (3, 20)	16563.135294117645
  (3, 21)	16224.623529411763
  (4, 5)	1.0
  (4, 20)	10834.1
  (4, 21)	10570.3
  (5, 9)	1.0
  (5, 20)	11237.6
  (5, 21)	10762.4
  (6, 13)	1.0
  (6, 20)	4183.9
  (6, 21)	4344.5
  (7, 6)	1.0
  (7, 20)	11499.3
  (7, 21)	11012.6
  (8, 17)	1.0
  (8, 20)	16563.135294117645
  (8, 21)	16224.623529411763
  (9, 16)	1.0
  (9, 20)	16563.135294117645
  (9, 21)	16224.623529411763
  (10, 8)	1.0
  (10, 20)	9544.2
  (10, 21)	9514.7
  (11, 15)	1.0
  (11, 20)	2314.2
  (11, 21)	2993.5
  (12, 7)	1.0
  (12, 20)	10274.3
  (12, 21)	10130.8
  (13, 12)	1.0
  (13, 20)	5676.6
  (13, 21)	5813.7
  (14, 11)	1.0
  (14, 20)	7133.3
  (14, 21)	7231.3
  (15, 3)	1.0
  (15, 20)	11509.1
  (15, 21)	10986.4


In [33]:
print(x_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (4, 22)>
  Coords	Values
  (0, 1)	1.0
  (0, 20)	11419.7
  (0, 21)	10714.6
  (1, 18)	1.0
  (1, 20)	140786.8
  (1, 21)	137909.4
  (2, 4)	1.0
  (2, 20)	11243.9
  (2, 21)	10845.1
  (3, 10)	1.0
  (3, 20)	8415.0
  (3, 21)	8450.9


In [34]:
print(y_train)

[10  1 13 17  8  9  2 15 17 17  6  0  7  3  4 14]


In [35]:
print(y_test)

[12 16 11  5]


In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)